# Generated by Django 5.0.6 on 2024-07-06 16:44

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adventure', 'Adventure'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller'), ('western', 'Western'), ('animation', 'Animation'), ('drama', 'Drama'), ('documentary', 'Documentary')], max_length=20),
        ),
    ]
