# Generated by Django 5.0.6 on 2024-07-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='movies/trailer'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movies/videos'),
        ),
    ]
