# Generated by Django 5.0.6 on 2024-08-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movies_video_alter_movies_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdb_rating',
            field=models.FloatField(default=0),
        ),
    ]
